Dianshang/urls.py
from django.contrib import admin
from django.urls import path,include
from app01 import views

urlpatterns = [
    # path('admin/', admin.site.urls),
    # path('tinymce/', include('tinymce.urls')),
    path('', include('goods.urls', namespace='goods')), # 商品模块
    path('', include('appUser.urls', namespace='appUser')),  # 商品模块
    path('', include('order.urls', namespace='order')),  # 订单模块
    path('', include('app01.urls', namespace='detail')),  # 商品详情
]

app01/urls.py
from django.contrib import admin
from django.urls import path

from app01 import views
app_name='detail'
urlpatterns = [
    path('admin/judge/list/', views.admin_judge_list,name='judge_list'),
    path('admin/words/list/', views.admin_words_list,name='user_words'),
    path('admin/reply/words/', views.admin_reply_words),
    path('admin/notice/list/', views.admin_notice_list,name='notice_add'),
    path('admin/notice/add/', views.admin_notice_add),
    path('admin/notice/edit/', views.admin_notice_edit),
    path('detail/', views.detail),
    path('goods/judge/', views.goods_judge),
]

appUser/urls.py
from django.contrib import admin
from django.urls import path
from appUser import views
app_name='appUser'
urlpatterns = [
    path('user/login/', views.user_login,name='user_login'),  #用户登录
    path('user/home/', views.user_home),
    path('user/info/', views.user_info),
    path('user/answer/', views.user_answer),
    path('user/detail/', views.user_detail),
    path('user/words/', views.user_words),
    path('admin/layout/', views.admin_layout),
    path('admin/login/', views.admin_login),
    path('admin/info/', views.admin_info,name='manager_list'), #管理员列表
    path('admin/form/', views.admin_form),
    path('user/list/', views.user_list,name='user_list'), # 用户列表
    path('user/add/', views.user_add),
    # path('user/delete/',views.user_delete),
    path('user/edit/', views.user_edit),
    #Git-hub测试语句！！！！！！！！！！
]

templates/Aorder_add.html
{% extends 'admin_layout.html' %}

{% block content %}

<div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">新建订单</h3>
            </div>
            <div class="panel-body">
                <form method="post">
                    {% csrf_token %}    <!--安全机制-->
                    <div class="form-group">
                        <label>订单号</label>
                        <input type="text" class="form-control" placeholder="订单号" name="number">
                    </div>

                    <div class="form-group">
                        <label>收货人姓名</label>
                        <input type="text" class="form-control" placeholder="收货人姓名" name="rname">
                    </div>

                    <div class="form-group">
                        <label>收货地址</label>
                        <input type="text" class="form-control" placeholder="收货地址" name="address">
                    </div>

                    <div class="form-group">
                        <label>邮编</label>
                        <input type="text" class="form-control" placeholder="邮编" name="pc">
                    </div>

                    <div class="form-group">
                        <label>联系电话</label>
                        <input type="text" class="form-control" placeholder="联系电话" name="tel">
                    </div>

                    <div class="form-group">
                        <label>收货时间</label>
                        <input type="text" class="form-control" placeholder="收货时间" name="rtime">
                    </div>

                    <div class="form-group">
                        <label>支付方式</label>
                        <select class="form-control" name="type">
                            <option value="1">WeChat Pay</option>
                            <option value="2">Alipay</option>
                        </select>
                    </div>

                    <div class="form-group">
                        <label>买家留言</label>
                        <input type="text" class="form-control" placeholder="买家留言" name="leaveword">
                    </div>

                    <div class="form-group">
                        <label>下单时间</label>
                        <input type="text" class="form-control" placeholder="收货时间" name="ptime">
                    </div>

                    <div class="form-group">
                        <label>下单人姓名</label>
                        <input type="text" class="form-control" placeholder="下单人姓名" name="pname">
                    </div>

                    <div class="form-group">
                        <label>订单状态</label>
                        <input type="text" class="form-control" placeholder="订单状态" name="state">
                    </div>

                    <div class="form-group">
                        <label>支付金额</label>
                        <input type="text" class="form-control" placeholder="支付金额" name="money">
                    </div>

                    <button type="submit" class="btn btn-primary">提 交</button>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

templates/admin_login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>管理员登录界面</title>
    <link rel="stylesheet" href="{% static 'plugins/dlmoban/css/index.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1-dist/css/bootstrap.min.css' %}">
</head>
<body>
<nav class="navbar navbar-default">
    <div class="container">
        <div class="navbar-header">
            <img alt="Brand" src="{% static 'img/logo.png' %}" width="70px" height="60px">
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-4">
            <a class="navbar-brand" href="#">首页</a>
        </div>
    </div>
</nav>

<canvas class="cavs" width="1575" height="1337"></canvas>

<div class="loginmain">
    <form action="{% url 'appUser:manager_list' %}">
    <div class="login-title">
        <span>管理员登录</span>
    </div>

    <div class="login-con">
        <div class="login-user">
            <div class="icon">
                <img src="{% static 'plugins/dlmoban/image/user_icon_copy.png' %}" alt="">
            </div>
            <input type="text" name="usernem" placeholder="用户名" autocomplete="off" value="">
        </div>
        <div class="login-pwd">
            <div class="icon">
                <img src="{% static 'plugins/dlmoban/image/lock_icon_copy.png' %}" alt="">
            </div>
            <input type="password" name="pwd" placeholder="密码" autocomplete="off" value="">
        </div>
        <div class="login-btn">
            <input type="submit" value="登录">
        </div>
    </div>
    </form>
</div>

<script src="{% static 'js/jquery-1.11.3.min.js' %}"></script>
<script src="{% static 'plugins/dlmoban/js/ban.js' %}"></script>
</body>
</html>

templates/admin_words_list.html
{% extends 'admin_layout.html' %}

{% block content %}
    <div class="container">
        <div class="panel panel-default">
      <!-- Default panel contents -->
          <div class="panel-heading">留言列表</div>

          <!-- Table -->
          <table class="table table-bordered">
            <thead>
              <tr>
                <th>ID</th>
                <th>留言内容</th>
                <th>留言时间</th>
                <th>留言者</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <th scope="row">1</th>
                <td>Mark</td>
                <td>Otto</td>
                <td>@mdo</td>
                  <td>
                      <a class="btn btn-danger" href="/admin/reply/words">回复</a>
                      <a class="btn btn-primary">删除</a>
                  </td>
              </tr>
              <tr>
                <th scope="row">2</th>
                <td>Jacob</td>
                <td>Thornton</td>
                <td>@fat</td>
                  <td>
                      <a class="btn btn-danger" href="/admin/reply/words">回复</a>
                      <a class="btn btn-primary">删除</a>
                  </td>
              </tr>
              <tr>
                <th scope="row">3</th>
                <td>Larry</td>
                <td>the Bird</td>
                <td>@twitter</td>
                  <td>
                      <a class="btn btn-danger" href="/admin/reply/words">回复</a>
                      <a class="btn btn-primary">删除</a>
                  </td>
              </tr>
            </tbody>
          </table>
        </div>
    </div>

{% endblock %}

templates/goods_judge.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>{% block title %}{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/footer.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/goods-judge.css' %}">
</head>
<body>
<div id="header">
      <!--顶部-->
    <div class="header_top">
        <div class="header_top_center">
            <div class="h_top_left">
                <div style="margin-right: 30px;display: inline-block">

                    <a href="index.html">商城首页</a>
                </div>
                嗷，欢迎来到老虎商城
            </div>
            <div class="h_top_right">
                <a href="login.html">登录</a>
                <a href="#">购物车</a>
                <a href="#">我的订单</a>
            </div>
        </div>
    </div>

	<div class="header_center">
        <div class="h_c_logo">
            <img src="{% static 'img/logo.png' %}" alt="">
        </div>
        <div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;商品评价</div>
        <div class="h_c_search">
            <form action="#" >
                <input type="text" placeholder="搜索 天猫 商品/品牌/店铺" class="t_input">
                <input type="submit" class="t_button" value="搜索">
            </form>
            <div class="hot">
                <a href="#">新款连衣裙</a>
                <a href="#">四件套</a>
                <a href="#">潮流T恤</a>
                <a href="#">时尚女鞋</a>
                <a href="#">短裤半身裙</a>
            </div>
        </div>
    </div>

	<div class="judge_con" >
        <div class="judge_goods fl">
            <ul >
                <li class="judge_size">
                    <a href="sku.url"><img src="../static/img/good2.jpg"></a>
                    <h4><a href="">苹果 AirPods2代 </a></h4>
                    <div class="">￥875</div>
                </li>
            </ul>
        </div>
        <div class="judge_goods_input fr">
            <div class="judge_item">
                <label>商品满意度</label>
                <div class="stars fl">
                    <a @mouseover="on_stars_mouseover(index, 1)" @mouseout="on_stars_mouseout(index)" @click="on_stars_click(index, 1)" class="star_off" :class="sku.score>=1?'light':''"></a>
					<a @mouseover="on_stars_mouseover(index, 2)" @mouseout="on_stars_mouseout(index)" @click="on_stars_click(index, 2)" class="star_off" :class="sku.score>=2?'light':''"></a>
					<a @mouseover="on_stars_mouseover(index, 3)" @mouseout="on_stars_mouseout(index)" @click="on_stars_click(index, 3)" class="star_off" :class="sku.score>=3?'light':''"></a>
					<a @mouseover="on_stars_mouseover(index, 4)" @mouseout="on_stars_mouseout(index)" @click="on_stars_click(index, 4)" class="star_off" :class="sku.score>=4?'light':''"></a>
					<a @mouseover="on_stars_mouseover(index, 5)" @mouseout="on_stars_mouseout(index)" @click="on_stars_click(index, 5)" class="star_off" :class="sku.score>=5?'light':''"></a>
                </div>
                <div class="score">分</div>
            </div>
            <div class="judge_item">
                <label>评分</label>
                <span data-type="description" class="rate-stars">
                    <label><input type="radio" value="1" name="description"  /> 一星</label>
                    <label><input type="radio" value="2" name="description"  /> 二星</label>
                    <label><input type="radio" value="3" name="description"  /> 三星</label>
                    <label><input type="radio" value="4" name="description"  /> 四星</label>
                    <label><input type="radio" value="5" name="description"  /> 五星</label>
                </span>
            </div>
            <div class="judge_item">
                <label>发表评价</label>
                <textarea class="judge_area" v-model="sku.comment"></textarea>
            </div>
            <div class="judge_item">
                <input type="input" value="提 交" class="judge_sub">
                <input type="checkbox" class="no_name"> 匿名评价
            </div>
        </div>
    </div>
</div>


<div id="footer">
	<div class="link">
		<a href="">关于我们</a>
		|
		<a href="">联系我们</a>
		|
		<a href="">人才招聘</a>
		|
		<a href="">商家入驻</a>
		|
		<a href="">广告服务</a>
		|
		<a href="">Hello社区</a>
		|
		<a href="">友情链接</a>
		|
		<a href="">销售联盟</a>
		|
		<a href="">手机商城</a>
		|
		<a href="">Hello公益</a>
	</div>
	<div class="Copyright">
		Copyright @ 2018-2019 superHRH.com 版权所有
	</div>
</div>
    {% block js %}{% endblock %}
</body>
</html>

templates/index.html
{% extends 'home_layout.html' %}
{% load static %}
{% block title %}老虎商城-商城首页{% endblock %}
{% block js %}
    <script type="text/javascript" src="js/paging.js"></script>
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <script src="{% static 'js/index.js' %}"></script>
{% endblock %}
{% block css %}
    <style>
        body{
            background:0 0 repeat-y url("{% static 'img/background.png' %}") ;
            background-size: cover;
        }
    </style>
{% endblock %}


{% block content %}
<!--中部-->
<div id="center">
    <!--广告轮播图-->
    <div id="ad">
        <div class="pic">
            <div class="content">
                <img src="../static/img/ad_1.png" alt="">
                <img src="../static/img/ad_2.png" alt="">
                <img src="../static/img/ad_3.png" alt="">
                <img src="../static/img/ad_4.png" alt="">
                <img src="../static/img/ad_5.png" alt="">
            </div>
            <div class="slider_ctl">
                <div class="right">></div>
                <ul class="index">
                </ul>
                <div class="left"><</div>
            </div>
        </div>
    </div>
    <!---公告--->
    <div id="board">
        <div class="bor_login bor_cl"></div>
        <div class="bor_ad bor_cl"></div>
        <div class="bor_border bor_cl"></div>
    </div>
</div>
<!--秒杀-->
<div id="ms">
    <div class="ms_top">
        <span>秒杀活动</span>
        <span>总有你想不到的低价</span>
    </div>
    <div class="ms_body">
        <ul>
            <li>
                <a href="#">
                    <img src="../static/img/goods/good1.png" alt="">
                    <p>小米（MI）小米净化器2智能家用卧室空气净化器除甲醛雾霾P</p>
                    <i class="yuan">￥</i><span class="price">599</span>
                </a>
            </li>
            <li>
                <a href="#">
                   <img src="../static/img/goods/good1.png" alt="">
                    <p>小米（MI）小米净化器2智能家用卧室空气净化器除甲醛雾霾P</p>
                    <i class="yuan">￥</i><span class="price">599</span>
                </a>
            </li>
            <li>
                <a href="#">
                <img src="../static/img/goods/good1.png" alt="">
                <p>小米（MI）小米净化器2智能家用卧室空气净化器除甲醛雾霾P</p>
                <i class="yuan">￥</i><span class="price">599</span>
            </a></li>
            <li>
                <a href="#">
                    <img src="../static/img/goods/good1.png" alt="">
                    <p>小米（MI）小米净化器2智能家用卧室空气净化器除甲醛雾霾P</p>
                    <i class="yuan">￥</i><span class="price">599</span>
                </a>
            </li>
            <li>
                <a href="#">
                <img src="../static/img/goods/good1.png" alt="">
                <p>小米（MI）小米净化器2智能家用卧室空气净化器除甲醛雾霾P</p>
                <i class="yuan">￥</i><span class="price">599</span>
             </a>
            </li>
        </ul>
    </div>
</div>
<!--热卖-->
<div id="hot_goods">
    <h3>热卖商品</h3>
    <div class="hot_goods_body">
       <ul>
           <li>
               <a href="">
                   <img src="../static/img/goods/goods6.png" alt="">
                   <p>小米（MI）小米净化器2智能家用卧室空气净化器除甲醛雾霾P</p>
                   <i class="yuan">￥</i><span class="price">599</span>
               </a>
           </li>
           <li>
               <a href="">
                   <img src="../static/img/goods/goods7.png" alt="">
                   <p>小米（MI）小米净化器2智能家用卧室空气净化器除甲醛雾霾P</p>
                   <i class="yuan">￥</i><span class="price">599</span>
               </a>
           </li>
           <li>
               <a href="">
                   <img src="../static/img/goods/goods8.png" alt="">
                   <p>小米（MI）小米净化器2智能家用卧室空气净化器除甲醛雾霾P</p>
                   <i class="yuan">￥</i><span class="price">599</span>
               </a>
           </li>
           <li>
               <a href="">
                   <img src="../static/img/goods/goods9.png" alt="">
                   <p>小米（MI）小米净化器2智能家用卧室空气净化器除甲醛雾霾P</p>
                   <i class="yuan">￥</i><span class="price">599</span>
               </a>
           </li>
           <li>
               <a href="">
                   <img src="../static/img/goods/goods10.png" alt="">
                   <p>小米（MI）小米净化器2智能家用卧室空气净化器除甲醛雾霾P</p>
                   <i class="yuan">￥</i><span class="price">599</span>
               </a>
           </li>
           <li>
               <a href="">
                   <img src="../static/img/goods/goods6.png" alt="">
                   <p>小米（MI）小米净化器2智能家用卧室空气净化器除甲醛雾霾P</p>
                   <i class="yuan">￥</i><span class="price">599</span>
               </a>
           </li>
           <li>
               <a href="">
                   <img src="../static/img/goods/goods7.png" alt="">
                   <p>小米（MI）小米净化器2智能家用卧室空气净化器除甲醛雾霾P</p>
                   <i class="yuan">￥</i><span class="price">599</span>
               </a>
           </li>
           <li>
               <a href="">
                   <img src="../static/img/goods/goods8.png" alt="">
                   <p>小米（MI）小米净化器2智能家用卧室空气净化器除甲醛雾霾P</p>
                   <i class="yuan">￥</i><span class="price">599</span>
               </a>
           </li>
       </ul>
    </div>
</div>
{% endblock %}

templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-CN">

<head>
    <meta charset="UTF-8">
    <title>用户登录页面</title>
    <link rel="stylesheet" href="{% static 'plugins/jqueryzcdl/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1/css/bootstrap.min.css' %}">
</head>

<body style="background-color:#FFF0F5">
<nav class="navbar navbar-default">
    <div class="container">
        <div class="navbar-header">
            <img alt="Brand" src="{% static 'img/logo.png' %}" width="70px" height="60px">
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-4">
            <a class="navbar-brand" href="#">首页</a>
        </div>
    </div>
</nav>
    <div class="materialContainer">
        <div class="box" style="background-color:white;">
            <div class="title">登录</div>
            <div class="input">
                <label for="name">用户名</label>
                <input type="text" name="name" id="name">
                <span class="spin"></span>
            </div>
            <div class="input">
                <label for="pass">密码</label>
                <input type="password" name="pass" id="pass">
                <span class="spin"></span>
            </div>
            <div class="button login">
                <button>
                    <span>登录</span>
                    <i class="fa fa-check"></i>
                </button>
            </div>
            <a href="/manager/login/" class="pass-forgot">管理员登录</a></a>
        </div>

        <div class="overbox">
            <div class="material-button alt-2">
                <span class="shape"></span>
            </div>
            <div class="title">注册</div>
            <div class="input">
                <label for="regname">用户名</label>
                <input type="text" name="regname" id="regname">
                <span class="spin"></span>
            </div>
            <div class="input">
                <label for="regpass">密码</label>
                <input type="password" name="regpass" id="regpass">
                <span class="spin"></span>
            </div>
            <div class="input">
                <label for="reregpass">确认密码</label>
                <input type="password" name="reregpass" id="reregpass">
                <span class="spin"></span>
            </div>
            <div class="button">
                <button>
                    <span>注册</span>
                </button>
            </div>
        </div>

    </div>
    <script src="{% static 'js/jquery-1.11.3.min.js' %}"></script>
    <script src="{% static 'plugins/jqueryzcdl/js/index.js' %}"></script>
</body>

</html>

templates/oder_processing.html
{% extends 'home_layout.html' %}
{% load static %}
{% block title %}美多商城-提交订单{% endblock %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/order_processing.css' %}">
{% endblock %}

{% block content %}

<h3 class="common_title">确认收货地址</h3>

<div class="common_list_con clearfix">
    <dl>
        <dt>寄送到：</dt>
        <dd v-for='address in addresses' :class="[(nowsite==address.id)?'current':'']" @click="nowsite=address.id">
            <input type="radio" name="get_site" :value="address.id" v-model="nowsite">四川省成都市双流区成都信息工程大学 （张三 收） 13722222222
        </dd>
    </dl>
    <a href="user_center_site.html" class="edit_site">编辑收货地址</a>
</div>

<h3 class="common_title">支付方式</h3>
<div class="common_list_con clearfix">
    <div class="pay_style_con clearfix">
        <input type="radio" name="pay_style" value="1" v-model="pay_method">
        <label class="cash">货到付款</label>
        <input type="radio" name="pay_style" value="2" v-model="pay_method">
        <label class="zhifubao"></label>
    </div>
</div>

<h3 class="common_title">商品列表</h3>

<div class="common_list_con clearfix">
    <ul class="goods_list_th clearfix">
        <li class="col01">商品名称</li>
        <li class="col03">商品价格</li>
        <li class="col04">数量</li>
        <li class="col05">小计</li>
    </ul>
    <ul class="goods_list_td clearfix" v-for="(sku,index) in skus">
        <li class="col01">1</li>
        <li class="col02"><img src="{% static 'img/good1.jpg' %}"></li>
        <li class="col03">标语印花棉质宽松 T 恤(黑色) - 男士</li>
        <li class="col05">50元</li>
        <li class="col06">1</li>
        <li class="col07">50元</li>
    </ul>
</div>

<h3 class="common_title">总金额结算</h3>

<div class="common_list_con clearfix">
    <div class="settle_con">
        <div class="total_goods_count">共<em>1</em>件商品，总金额<b>60元</b></div>
        <div class="transit">运费：<b>10元</b></div>
        <div class="total_pay">实付款：<b>60元</b></div>
    </div>
</div>

<div class="order_submit clearfix">
    <a href="/shop/user/order/success/" id="order_btn">提交订单</a>
</div>

{% endblock %}

{% block js %}

<script src="{% static 'plugins/bootstrap-3.4.1/js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
{% endblock %}

templates/order_list.html
{% extends 'home_layout.html' %}
{% load static %}
{% block title %}我的订单{% endblock %}

{% block css %}
	<link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1/css/bootstrap.min.css' %}">
{% endblock %}

{% block content %}
<div class="container">

        <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">
                <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                订单列表
            </div>

            <!-- Table -->
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>编号</th>
                    <th>订单号</th>
                    <th>收货人姓名</th>
                    <th>收货地址</th>
                    <th>邮编</th>
                    <th>联系电话</th>
                    <th>收货时间</th>
                    <th>支付方式</th>
                    <th>买家留言</th>
                    <th>下单时间</th>
                    <th>下单人姓名</th>
                    <th>订单状态</th>
                    <th>支付金额</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>1</td>
                    <td>1000001</td>
                    <td>李四</td>
                    <td>四川成都</td>
                    <td>041600</td>
                    <td>13313451234</td>
                    <td>2022.1.1</td>
                    <td>WeChat Pay</td>
                    <td>null</td>
                    <td>2021.12.21</td>
                    <td>王五</td>
                    <td>派送成功</td>
                    <td>18.99</td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

{% block js %}
<script src="{% static 'plugins/bootstrap-3.4.1/js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
{% endblock %}

templates/user_home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>用户中心</title>
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1-dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/info.css' %}">
</head>
<body>
<div class="nav-left">
    <div class="logoname">用户中心</div>
    <div class="navName">导航</div>
    <ul class="nav nav-tabs nav-stacked">
        <li role="presentation"><a class="nav-li active" href="../info" target="iframe"><i class='glyphicon glyphicon-home'></i>主页</a></li>
        <li role="presentation"><a class="nav-li" href="../answer" target="iframe"><i class='glyphicon glyphicon-envelope'></i>消息中心<span class="badge">2</span></a></li>
        <li role="presentation"><a class="nav-li" href="../detail" target="iframe"><i class='glyphicon glyphicon-user'></i>个人信息修改</a></li>
        <li role="presentation"><a class="nav-li" href="../words" target="iframe"><i class='glyphicon glyphicon-comment'></i>留言板</a></li>
    </ul>
</div >

<div class="nav-right">
    <div class="nav-top">
        <div style="text-align: right;"><a class="nav-li">首页</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a class="nav-li">注销</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</div>
    </div>
    <div class="content-page" ref="cPage">
        <iframe name="iframe" width="100%" height="100%" frameborder="0" src="../info"></iframe>
    </div>
</div>
<script src="{% static 'js/jquery-1.11.3.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap-3.4.1-dist/js/bootstrap.min.js' %}"></script>
</body>
</html>